export const carData = [
    {
      id: 1,
      brand: "Tesla",
      model: "Model S",
      price: 79999,
      weight: "2,241 kg",
      rating: 4.8,
      image: "/images/TeslaModelS.jpg", // Replace with actual image URLs
    },
    {
      id: 2,
      brand: "Ford",
      model: "Mustang",
      price: 55999,
      weight: "1,740 kg",
      rating: 4.5,
      image: "/images/FordMustang.jpg",
    },
    {
      id: 3,
      brand: "BMW",
      model: "i8",
      price: 147500,
      weight: "1,485 kg",
      rating: 4.7,
      image: "/images/BMWi8.jpg",
    },
    {
      id: 4,
      brand: "Audi",
      model: "R8",
      price: 169900,
      weight: "1,595 kg",
      rating: 4.9,
      image: "/images/AudiR8.jpg",
    },
    {
      id: 5,
      brand: "Mercedes-Benz",
      model: "C-Class",
      price: 42900,
      weight: "1,610 kg",
      rating: 4.6,
      image: "/images/Mercedes-BenzC-Class.jpg",
    },
    {
      id: 6,
      brand: "Toyota",
      model: "Camry",
      price: 25470,
      weight: "1,500 kg",
      rating: 4.4,
      image: "/images/ToyotaCamry.jpg",

    },
    {
      id: 7,
      brand: "Chevrolet",
      model: "Corvette",
      price: 59995,
      weight: "1,530 kg",
      rating: 4.8,
      image: "https://via.placeholder.com/300x200?text=Chevrolet+Corvette",
    },
    {
      id: 8,
      brand: "Porsche",
      model: "911",
      price: 101200,
      weight: "1,503 kg",
      rating: 4.9,
      image: "https://via.placeholder.com/300x200?text=Porsche+911",
    },
    {
      id: 9,
      brand: "Honda",
      model: "Civic",
      price: 21950,
      weight: "1,400 kg",
      rating: 4.3,
      image: "https://via.placeholder.com/300x200?text=Honda+Civic",
    },
    {
      id: 10,
      brand: "Nissan",
      model: "GT-R",
      price: 113540,
      weight: "1,700 kg",
      rating: 4.8,
      image: "https://via.placeholder.com/300x200?text=Nissan+GT-R",
    },
    // Indian cars added below
    {
      id: 11,
      brand: "Tata",
      model: "Nexon",
      price: 800000, // Price in INR
      weight: "1,350 kg",
      rating: 4.4,
      image: "https://via.placeholder.com/300x200?text=Tata+Nexon",
    },
    {
      id: 12,
      brand: "Mahindra",
      model: "XUV700",
      price: 2200000, // Price in INR
      weight: "1,800 kg",
      rating: 4.7,
      image: "https://via.placeholder.com/300x200?text=Mahindra+XUV700",
    },
    {
      id: 13,
      brand: "Maruti Suzuki",
      model: "Swift",
      price: 600000, // Price in INR
      weight: "900 kg",
      rating: 4.2,
      image: "https://via.placeholder.com/300x200?text=Maruti+Suzuki+Swift",
    },
    {
      id: 14,
      brand: "Hyundai",
      model: "Creta",
      price: 1040000, // Price in INR
      weight: "1,300 kg",
      rating: 4.5,
      image: "https://via.placeholder.com/300x200?text=Hyundai+Creta",
    },
    {
      id: 15,
      brand: "BMW",
      model: "X5",
      price: 9000000, // Price in INR
      weight: "2,100 kg",
      rating: 4.8,
      image: "https://via.placeholder.com/300x200?text=BMW+X5",
    },
    // More cars under the same brands
    {
      id: 16,
      brand: "Tesla",
      model: "Model 3",
      price: 39999,
      weight: "1,611 kg",
      rating: 4.7,
      image: "https://via.placeholder.com/300x200?text=Tesla+Model+3",
    },
    {
      id: 17,
      brand: "Ford",
      model: "Explorer",
      price: 43999,
      weight: "2,270 kg",
      rating: 4.6,
      image: "https://via.placeholder.com/300x200?text=Ford+Explorer",
    },
    {
      id: 18,
      brand: "Chevrolet",
      model: "Tahoe",
      price: 64995,
      weight: "2,600 kg",
      rating: 4.7,
      image: "https://via.placeholder.com/300x200?text=Chevrolet+Tahoe",
    },
    {
      id: 19,
      brand: "Hyundai",
      model: "Tucson",
      price: 27000,
      weight: "1,500 kg",
      rating: 4.6,
      image: "https://via.placeholder.com/300x200?text=Hyundai+Tucson",
    },
    {
      id: 20,
      brand: "BMW",
      model: "M4",
      price: 71500,
      weight: "1,700 kg",
      rating: 4.8,
      image: "https://via.placeholder.com/300x200?text=BMW+M4",
    },
  ];
  